[package]
name = "mini_nmap"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
hex = "0.4.3"
hex_fmt = "0.3.0"
itertools = "0.14.0"
tun-tap = "0.1.4"

